name: Expo CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install EAS CLI
        run: npm install -g eas-cli@latest

      - name: Install dependencies
        run: yarn install 2> >(grep -v warning 1>&2)

      - name: Run tests
        run: yarn test

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Gem
        run: yarn add global rubygems gem git

      - name: Install Fastlane
        run: gem install fastlane

      - name: Build Expo project
        run: eas build -p ios --non-interactive
        env:
          CI: 1
          EAS_NO_VCS: 1
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}

      - name: Build Expo project
        run: eas build -p android --non-interactive
        env:
          CI: 1
          EAS_NO_VCS: 1
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}


      - name: Install Fastlane
        run: gem install fastlane

      - name: Authenticate with Apple
        run: fastlane spaceauth -u ${{ secrets.APPLE_ID }}
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}

      - name: Upload to TestFlight
        run: |
          fastlane pilot upload --ipa path/to/your-app.ipa
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}